services:
  postgres:
    container_name: coursesapi_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: courses_db
    volumes:
      - courses_vol:/var/lib/postgresql/data

volumes:
  courses_vol: